blog/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:slug>', views.BlogPostDetailView.as_view(), name='detail')
]

pagination/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('blog/', include('blog.urls'), name='blog')
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse


# Create your models here.

class BlogPost(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(default='')

    def get_truncated(self):
        return self.body[:200] + ' ...'

    def __str__(self):
        return self.title[:100]

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

blog/views.py
from django.shortcuts import render, get_list_or_404
from .models import BlogPost
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import DetailView


# Create your views here.


def index(request):
    objects = BlogPost.objects.all().order_by('id').reverse()
    page = request.GET.get('page', 1)

    paginator = Paginator(objects, 3)

    try:
        blog_posts = paginator.page(page)
    except EmptyPage:
        blog_posts = paginator.page(paginator.num_pages)
    except:
        blog_posts = paginator.page(1)

    context = {
        'blog_posts': blog_posts
    }

    return render(request, 'blog/bloglist.html', context=context)


class BlogPostDetailView(DetailView):
    model = BlogPost
    context_object_name = 'blog_post'

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="body-container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

blog/templates/blog/bloglist.html
{% extends 'base.html' %}

{% block content %}
    <div class="blog-list">
        {% for blog_post in blog_posts %}
            <div class="blog-item">
                <a href="{{ blog_post.get_absolute_url }}"><h2>{{ blog_post.title|title }}</h2></a><span
                    class="small"
            >{{ blog_post.added | timesince }} ago</span>
                <p>{{ blog_post.get_truncated }}</p>
            </div>
        {% endfor %}
    </div>
    <div class="page-bar">
        {% if blog_posts.has_other_pages %}
            <ul class="pagination">
                {% if blog_posts.has_previous %}
                    <li><a href="?page={{ blog_posts.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in blog_posts.paginator.page_range %}
                    {% if blog_posts.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if blog_posts.has_next %}
                    <li><a href="?page={{ blog_posts.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="blog-list">
        <div class="blog-detail-item">
            <h2>{{ blog_post.title|title }}</h2><span class="small">{{ blog_post.added | timesince }}
            ago</span>
            <p>{{ blog_post.body }}</p>
            </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="body-container">
    <header>
        {% include 'nav.html' %}
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>

    </footer>

    <script src="{% static 'js/main.js' %}"></script>
</div>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div><h1>You are home</h1></div>
{% endblock %}

templates/nav.html
<nav class="nav main-nav">
    <a href="{% url 'home' %}">Home</a>
    <a href="{% url 'blog:index' %}">Blog</a>
    <a href="{% url 'admin:index' %}">Admin</a>
</nav>